---
language: python
services: docker

env:
  global:
    - ROLE_NAME: kibana
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: ubuntu1804

install:
  # Install test dependencies.
  - pip install molecule docker

script:
  - molecule test              
